spring:
  config:
    activate:
      on-profile: prod

  # MySQL 설정
  datasource:
    url: jdbc:mysql://k12d108.p.ssafy.io:3306/storycut

  # MongoDB, Redis 설정
  data:
    redis:
      host: redis
      port: 6379
    mongodb:
      host: mongo
      port: 27017
      database: storycut

server:
  port: 8080

app:
  baseUrl: https://k12d108.p.ssafy.io
  # 앱 리다이렉션 스키마 설정
  mobile:
    redirectScheme: stroycut://oauth2/redirect

logging:
  file:
    name: /logs/app.log
  level:
    org.springframework.security: WARN  # Security 관련 로그 줄이기
    org.springframework.web.filter.CommonsRequestLoggingFilter: WARN  # 요청 로그 줄이기
    com.finbattle.global.common.filter.JWTFilter: WARN  # JWT 필터 로깅 최소화
    org.springframework.web: WARN  # Spring Web 관련 로그 최소화
    org.apache.coyote.http11: WARN  # Tomcat 요청 로그 줄이기
    org.apache.tomcat: WARN  # Tomcat 관련 상세 로그 줄이기

  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
